from .employee import EmployeeSerializer, EmployeeCreateSerializer, EmployeeUpdateSerializer, EmployeeDeleteSerializer
from .outlet import OutletSerializer, OutletCreateSerializer, OutletUpdateSerializer, OutletDeleteSerializer
from .visit import VisitSerializer, VisitCreateSerializer, VisitUpdateSerializer