# Generated by Django 3.2.8 on 2022-09-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test17', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test17.outlet', verbose_name='Торговая точка'),
        ),
    ]
